# List

In [ ]:
number = [1, 2, 3]

In [ ]:
number

[1, 2, 3]

In [ ]:
number = list(range(20))
number

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
number = [0] * 10
number

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Mixing data types

In [ ]:
mixed = ['a', 1, 2.0, [12, {}]]

In [ ]:
type(mixed)

list

# Indexing

In [ ]:
number

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
number[3]

3

In [ ]:
number[-4]

16

# Adding to a list

In [ ]:
list_letters = []
list_letters

[]

In [ ]:
list_letters = ['a']
list_letters

['a']

In [ ]:
list_letters.append('b')
list_letters

['a', 'b']

In [ ]:
list_letters.insert(0, 'z')
list_letters

['z', 'a', 'b']

In [ ]:
list_letters.append('d')
list_letters

['z', 'a', 'b', 'd']

In [ ]:
list_letters.insert(3, 'c')
list_letters

['z', 'a', 'b', 'c', 'd']

In [ ]:
list_letters [0] = 'June'
list_letters

['June', 'a', 'b', 'c', 'd']

# Swap two items

In [ ]:
list_letters [1], list_letters [2] = list_letters [2], list_letters [1]
list_letters

['June', 'b', 'a', 'c', 'd']

#Removing items from list

In [ ]:
list_letters.pop(0)
list_letters

['b', 'a', 'c', 'd']

#Numpy

pandas
numpy

In [ ]:
import numpy as np

In [ ]:
zeros_array = np.zeros((4, 6))
zeros_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
[[0]*6]*4

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

In [ ]:
puzzle = np.arange(9)
puzzle

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
puzzle.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Pandas

In [ ]:
import pandas as pd

In [ ]:
first_name = ['henry', 'molly', 'david']
ages = [30, 25, 45]
gender = ['M', 'F', 'M']

In [ ]:
df_friends = pd.DataFrame({'first_name' : first_name, 'age' : ages, 'gender' : gender})

In [ ]:
df_friends

first_name  age gender
0      henry   30      M
1      molly   25      F
2      david   45      M

In [ ]:
df_friends['age'] >= 30

0     True
1    False
2     True
Name: age, dtype: bool

In [ ]:
df_friends.iloc[0]

first_name    henry
age              30
gender            M
Name: 0, dtype: object

In [22]:
df_friends.groupby(['age']).mean()

<ipython-input-22-f9f954b205d5>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_friends.groupby(['age']).mean()


Empty DataFrame
Columns: []
Index: [25, 30, 45]

#Array Slicing

# Data Collection